// The built-in SDLC recipe library, written against ./types.ts.
//
// House rules for every prompt here (pinned by test/recipes.library.test.ts):
// - short: a small on-device model has a 4k window shared with the attached
//   context, so instructions stay well under ~150 words;
// - the exact output format is stated;
// - the model is told to name what it is unsure about instead of inventing;
// - `{{input}}` carries what the person typed (it may be empty). Attachments
//   are appended by the chat app in its own format - never referred to by
//   position ("the file below", "the first attachment").
// - `localFriendly` is honest: false where a 1-3B model would produce
//   confident nonsense (security review, API design, large-diff judgement).

import type { Recipe } from "./types";

/** Shared closing instruction: be explicit about uncertainty. */
const UNSURE =
  "If the provided material does not say something, do not invent it: list it under a final \"Unsure / needs confirmation\" heading.";

/** The same rule for outputs that must stay machine-readable (CSV, JSON, code). */
const UNSURE_INLINE =
  "Do not invent facts the material does not support; mark any assumption with a short comment or note where the format allows it.";

export const BUILT_IN_RECIPES: Recipe[] = [
  // ------------------------------------------------------------------ PLAN
  {
    id: "story-to-acceptance-criteria",
    name: "Acceptance criteria from a story",
    description: "Turns a user story into Given/When/Then acceptance criteria, edge cases and open questions for product owners and testers.",
    phase: "plan",
    roles: ["product", "tester"],
    slash: "ac",
    context: ["selection", "file", "page"],
    prompt: [
      "You are a product owner and QA lead writing acceptance criteria.",
      "Story or requirement: {{input}}",
      "Output Markdown with exactly these sections:",
      "## Acceptance criteria - numbered scenarios, each as Given / When / Then lines, one behaviour per scenario.",
      "## Edge cases - bullets covering empty, invalid, boundary, permission and failure paths.",
      "## Out of scope - bullets, only if the story implies them.",
      "## Open questions - what the story leaves ambiguous, phrased as questions for the product owner.",
      "Do not add features the story does not ask for. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "spec-to-task-checklist",
    name: "Spec to implementation tasks",
    description: "Breaks a spec or story into an ordered, reviewable implementation checklist for developers and product owners.",
    phase: "plan",
    roles: ["developer", "product"],
    slash: "tasks",
    context: ["selection", "file", "page"],
    prompt: [
      "You are a senior engineer planning implementation work.",
      "Spec: {{input}}",
      "Output a Markdown checklist (\"- [ ] ...\") grouped under short headings (e.g. Data, Backend, UI, Tests, Rollout).",
      "Each task: one verb-first line small enough for a single pull request, with its dependency in brackets when it has one.",
      "Order tasks so each can be merged and verified on its own. Include tests, migrations, feature flags and docs where they apply.",
      "End with \"Estimate risk:\" and one sentence on the riskiest task. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "feature-risks-and-unknowns",
    name: "Risks and unknowns for a feature",
    description: "Lists technical, product, security and delivery risks of a proposed feature with mitigations, for architects and product managers.",
    phase: "plan",
    roles: ["architect", "product"],
    slash: "risks",
    context: ["selection", "file", "page"],
    prompt: [
      "You are a staff architect and product manager doing a pre-mortem.",
      "Feature: {{input}}",
      "Output a Markdown table with columns: Risk | Category (technical, product, security, data, operational, delivery) | Likelihood (H/M/L) | Impact (H/M/L) | Mitigation or spike.",
      "List at most 10 risks, most severe first. Be specific to this feature; skip generic risks that apply to any project.",
      "Then a section \"## Unknowns to resolve first\" with the questions that would most change the plan. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: true,
    builtIn: true,
  },

  // ---------------------------------------------------------------- DESIGN
  {
    id: "architecture-decision-record",
    name: "Architecture decision record",
    description: "Drafts an ADR (context, options, decision, consequences) from notes or code, for architects.",
    phase: "design",
    roles: ["architect", "developer"],
    slash: "adr",
    context: ["selection", "file", "page"],
    prompt: [
      "You are a staff architect drafting an Architecture Decision Record.",
      "Decision to record: {{input}}",
      "Output Markdown in this template:",
      "# ADR: <short title>",
      "Status: Proposed",
      "## Context - the forces and constraints, facts only.",
      "## Options considered - 2-4 options, each with pros and cons bullets.",
      "## Decision - the chosen option and the main reason.",
      "## Consequences - positive, negative, and what becomes harder later.",
      "## Follow-ups - concrete actions.",
      "If no decision has been made, leave Decision as \"TBD\" and recommend one with its trade-off. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown", offerNewFile: true, languageId: "markdown" },
    localFriendly: false,
    builtIn: true,
  },
  {
    id: "code-to-mermaid-diagram",
    name: "Diagram this code (Mermaid)",
    description: "Draws a Mermaid sequence or class diagram of the attached code for architects and developers.",
    phase: "design",
    roles: ["architect", "developer"],
    slash: "diagram",
    context: ["selection", "file"],
    requiresContext: true,
    prompt: [
      "You are a software architect documenting code.",
      "Diagram type requested: {{input}}",
      "If no type is requested, choose sequenceDiagram for a call flow and classDiagram for types and their relationships.",
      "Output exactly one ```mermaid code block that renders without errors, then at most three bullets explaining what it shows.",
      "Use only names that appear in the code. Keep it under 25 nodes or messages; group or omit trivial helpers.",
      "Do not put quotes, parentheses or semicolons inside participant or class names. " + UNSURE,
    ].join("\n"),
    output: { kind: "mermaid", offerNewFile: true, languageId: "markdown" },
    localFriendly: false,
    builtIn: true,
  },
  {
    id: "api-design-review",
    name: "API design review",
    description: "Reviews an API contract (REST, GraphQL, RPC or a public interface) for consistency, evolvability and safety, for architects and reviewers.",
    phase: "design",
    roles: ["architect", "reviewer"],
    slash: "api-review",
    context: ["selection", "file", "diff"],
    requiresContext: true,
    prompt: [
      "You are a staff engineer reviewing an API design.",
      "Focus from the user: {{input}}",
      "Check: naming and consistency, resource and verb choice, status and error model, pagination and filtering, idempotency and retries, versioning and backward compatibility, authentication and authorization, input validation, and documentation gaps.",
      "Output Markdown: a one-line verdict, then a table Issue | Where | Severity (blocker, major, minor) | Suggested change, most severe first.",
      "Only report issues visible in the material; do not restate what is fine. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: false,
    builtIn: true,
  },

  // ----------------------------------------------------------------- BUILD
  {
    id: "scaffold-from-description",
    name: "Scaffold from a description",
    description: "Generates a small, working starting point (file, component, script or service) from a plain-language description, for developers.",
    phase: "build",
    roles: ["developer"],
    slash: "scaffold",
    context: ["file", "selection"],
    prompt: [
      "You are a senior developer writing a clean starting point.",
      "Build this: {{input}}",
      "If code is provided, match its language, framework, naming and style.",
      "Output one fenced code block containing a single complete file with the imports it needs, no placeholders like \"...\", and TODO comments only where a real decision is needed.",
      "Before the block, one line naming the file path you suggest. After it, at most three bullets on how to run or wire it in.",
      UNSURE_INLINE,
    ].join("\n"),
    output: { kind: "code", offerNewFile: true },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "explain-for-newcomer",
    name: "Onboarding walkthrough of this code",
    description: "Explains code to someone new to the codebase: purpose, flow, key concepts and where to start changing it.",
    phase: "build",
    roles: ["developer", "tester"],
    slash: "onboard",
    context: ["selection", "file"],
    requiresContext: true,
    prompt: [
      "You are a patient senior engineer onboarding a new teammate.",
      "Their question, if any: {{input}}",
      "Output Markdown with these sections:",
      "## What it does - two or three sentences, no jargon left unexplained.",
      "## How it flows - numbered steps following the main path through the code.",
      "## Key concepts - bullets for patterns, domain terms and dependencies a newcomer must know.",
      "## Watch out for - side effects, hidden coupling, surprising behaviour.",
      "## Where to start - which function to read or change first for a typical task.",
      "Refer to real names from the code. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "decode-regex-sql-shell",
    name: "Decode a regex, SQL query or shell command",
    description: "Explains a regular expression, SQL statement or shell command piece by piece, with pitfalls and a safer variant, for developers and DevOps.",
    phase: "build",
    roles: ["developer", "devops"],
    slash: "decode",
    context: ["selection", "terminal"],
    prompt: [
      "You are an expert in regular expressions, SQL and Unix/PowerShell shells.",
      "Expression or command: {{input}}",
      "Identify which kind it is and the dialect if it matters (PCRE vs JavaScript, PostgreSQL vs MySQL, bash vs PowerShell).",
      "Output Markdown:",
      "1. One-sentence summary of what it does.",
      "2. A table Part | Meaning, token by token or clause by clause.",
      "3. Examples: two inputs or cases it handles and one it does not.",
      "4. Pitfalls: performance, injection, destructive flags, quoting or locale issues.",
      "5. A safer or clearer equivalent, only if one exists. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "refactor-plan",
    name: "Refactor plan for a messy file",
    description: "Proposes a stepwise, behaviour-preserving refactor plan for tangled code, for developers and architects.",
    phase: "build",
    roles: ["developer", "architect"],
    slash: "refactor",
    context: ["file", "selection", "diagnostics"],
    requiresContext: true,
    prompt: [
      "You are a staff engineer planning a safe refactor.",
      "Goal or constraint from the user: {{input}}",
      "Output Markdown:",
      "## Smells - bullets naming each problem and where it is (function or line range).",
      "## Plan - numbered steps; each step is behaviour-preserving, small enough for one commit, and says how to verify it (existing test, new characterization test, or manual check).",
      "## Target shape - a short sketch of the resulting modules or functions.",
      "## Do not touch - what should stay as is, and why.",
      "Do not rewrite the code in full. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: false,
    builtIn: true,
  },

  // ------------------------------------------------------------------ TEST
  {
    id: "requirements-to-test-cases-csv",
    name: "Test cases from requirements (CSV)",
    description: "Derives manual test cases from requirements as CSV ready to import into a test-management tool, for testers.",
    phase: "test",
    roles: ["tester", "product"],
    slash: "testcases",
    context: ["selection", "file", "page"],
    prompt: [
      "You are a QA lead designing test cases.",
      "Requirements: {{input}}",
      "Output ONLY CSV, no prose and no code fence, with this header row:",
      "ID,Title,Preconditions,Steps,Expected result,Priority",
      "IDs are TC-001, TC-002 and so on. Steps are numbered inside one quoted cell separated by \"; \". Priority is High, Medium or Low.",
      "Cover the happy path, validation, boundaries, permissions, error handling and at least one negative case per requirement.",
      "Quote any cell containing a comma. If a requirement is ambiguous, add a row whose Title starts with \"QUESTION:\" instead of guessing.",
    ].join("\n"),
    output: { kind: "csv", languageId: "csv", offerNewFile: true },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "unit-tests-for-selection",
    name: "Unit tests for this code",
    description: "Writes focused unit tests for the selected code in the project's own test framework, for developers and testers.",
    phase: "test",
    roles: ["developer", "tester"],
    slash: "unit",
    context: ["selection", "file"],
    requiresContext: true,
    prompt: [
      "You are a senior developer writing unit tests.",
      "Framework or focus from the user: {{input}}",
      "Use the test framework and style already used in the code's language (e.g. vitest or jest, pytest, JUnit 5, Go testing); if you cannot tell, say which one you picked.",
      "Output one fenced code block with a complete test file: happy path, boundaries, invalid input, and error paths. One behaviour per test, descriptive names, no network or clock dependence (mock them).",
      "After the block, list behaviours you could not test and why. " + UNSURE_INLINE,
    ].join("\n"),
    output: { kind: "code", offerNewFile: true },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "test-data-from-schema",
    name: "Realistic test data from a schema",
    description: "Generates realistic, varied test data from a schema, type or table definition as JSON, CSV or SQL inserts, for testers and developers.",
    phase: "test",
    roles: ["tester", "developer"],
    slash: "testdata",
    context: ["selection", "file"],
    prompt: [
      "You are a test-data engineer.",
      "Schema, type or table plus any wishes (format, row count): {{input}}",
      "Default to a JSON array of 10 records; use CSV or SQL INSERT statements only if asked.",
      "Respect every type, required field, enum, length and foreign key you can see. Mix typical values with edge cases: empty strings where allowed, maximum lengths, unicode names, zero and negative numbers, boundary dates.",
      "Use obviously fake data (example.com emails, 555 phone numbers); never real people.",
      "Output only one fenced code block. " + UNSURE_INLINE,
    ].join("\n"),
    output: { kind: "json", languageId: "json", offerNewFile: true },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "playwright-test-from-page",
    name: "Playwright test from this page",
    description: "Writes a Playwright end-to-end test for the current page using its real interactive elements, for testers.",
    phase: "test",
    roles: ["tester", "developer"],
    slash: "e2e",
    context: ["pageElements", "page"],
    requiresContext: true,
    prompt: [
      "You are a test automation engineer writing Playwright tests in TypeScript.",
      "Scenario to cover: {{input}}",
      "If no scenario is given, test the page's primary user flow.",
      "Use only elements present in the page context. Prefer getByRole with the accessible name, then getByLabel, getByText, and getByTestId; never XPath or brittle CSS chains.",
      "Output one fenced typescript block: import { test, expect } from \"@playwright/test\"; one test.describe; web-first assertions (toBeVisible, toHaveURL, toHaveText); no fixed waits.",
      "After the block, list steps you could not automate from the page context. " + UNSURE_INLINE,
    ].join("\n"),
    output: { kind: "code", languageId: "typescript", offerNewFile: true },
    localFriendly: false,
    builtIn: true,
  },
  {
    id: "bug-report-writer",
    name: "Write a bug report",
    description: "Turns an observation, log excerpt or page into a clear, reproducible bug report with severity, for testers.",
    phase: "test",
    roles: ["tester", "developer", "product"],
    slash: "bug",
    context: ["selection", "terminal", "page", "diagnostics"],
    prompt: [
      "You are a QA engineer filing a bug.",
      "What happened: {{input}}",
      "Output Markdown in this template:",
      "**Title:** <component>: <symptom> when <trigger>",
      "**Severity:** Critical / Major / Minor / Trivial - with a one-line justification",
      "**Environment:** only what the material shows (app version, browser, OS, URL); otherwise \"not provided\"",
      "**Steps to reproduce:** numbered",
      "**Expected result:**",
      "**Actual result:** include the exact error text if present",
      "**Evidence:** key log lines, trimmed",
      "**Notes:** frequency, workaround, suspected area",
      UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "explain-failing-test",
    name: "Why is this test failing?",
    description: "Reads failing test output and explains the likely cause and the fix to try first, for developers and testers.",
    phase: "test",
    roles: ["developer", "tester"],
    slash: "why-fail",
    context: ["terminal", "selection", "file", "diagnostics"],
    requiresContext: true,
    prompt: [
      "You are a senior developer triaging a failing test.",
      "Extra detail from the user: {{input}}",
      "Output Markdown:",
      "**Failing test:** name and assertion.",
      "**What it expected vs what it got:** in plain words.",
      "**Most likely cause:** one paragraph; say whether the bug is probably in the code under test, the test itself, test data or environment (flaky timing, order dependence, missing setup).",
      "**Fix to try first:** concrete change, with a short code snippet if useful.",
      "**If that is not it:** up to three next checks.",
      UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "accessibility-review-page",
    name: "Accessibility review of this page",
    description: "Checks the current page against WCAG 2.2 AA from its elements and text, with fixes, for testers and product people.",
    phase: "test",
    roles: ["tester", "product", "developer"],
    slash: "a11y",
    context: ["pageElements", "page"],
    requiresContext: true,
    prompt: [
      "You are an accessibility specialist reviewing a web page against WCAG 2.2 AA.",
      "Focus from the user: {{input}}",
      "From the page context, check: missing or vague accessible names, buttons or links without text, form fields without labels, heading structure, link text like \"click here\", images without alt text, and keyboard-reachability hints.",
      "Output a Markdown table: Issue | Element (role and name) | WCAG criterion | Severity (high, medium, low) | Fix.",
      "Then list what cannot be judged from this context (colour contrast, focus order, screen-reader announcements) and needs a manual or tool check. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: false,
    builtIn: true,
  },

  // ---------------------------------------------------------------- REVIEW
  {
    id: "security-review-diff",
    name: "Security review of the changes",
    description: "Reviews a diff for OWASP Top 10 style vulnerabilities with severity and fixes, for reviewers and architects.",
    phase: "review",
    roles: ["reviewer", "architect", "developer"],
    slash: "secure",
    context: ["diff", "selection", "file"],
    requiresContext: true,
    prompt: [
      "You are an application security engineer reviewing a code change.",
      "Focus from the user: {{input}}",
      "Check against OWASP Top 10: injection (SQL, command, template), broken access control, authentication and session flaws, sensitive data exposure and secrets in code, SSRF, insecure deserialization, XSS, path traversal, vulnerable dependencies, and missing logging of security events.",
      "Output a Markdown table: Finding | File and line | Severity (critical, high, medium, low) | Why it is exploitable | Fix. Most severe first.",
      "Report only issues introduced or touched by the change. If you find none, say so plainly; do not pad. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: false,
    builtIn: true,
  },
  {
    id: "pr-description-from-diff",
    name: "Pull request description",
    description: "Writes a pull request title and description (summary, changes, testing notes, risk) from the diff, for developers and reviewers.",
    phase: "review",
    roles: ["developer", "reviewer"],
    slash: "pr",
    context: ["diff", "gitlog"],
    requiresContext: true,
    prompt: [
      "You are a developer opening a pull request.",
      "Ticket, motivation or notes from the author: {{input}}",
      "Output Markdown in this template:",
      "# <imperative title, max 72 characters>",
      "## Summary - why this change, in two or three sentences.",
      "## Changes - bullets grouped by area, describing behaviour, not line edits.",
      "## Testing - what was tested and how; if the diff has no tests, say \"No automated tests in this change\".",
      "## Risk and rollout - Low / Medium / High with the reason, migrations, flags, and how to roll back.",
      "Do not claim tests were run unless the material shows it. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "review-checklist-for-diff",
    name: "Review checklist for these changes",
    description: "Builds a change-specific checklist a reviewer can work through, for reviewers.",
    phase: "review",
    roles: ["reviewer", "developer"],
    slash: "checklist",
    context: ["diff", "selection"],
    requiresContext: true,
    prompt: [
      "You are a principal engineer preparing a code review.",
      "Reviewer's focus: {{input}}",
      "Output a Markdown checklist (\"- [ ] ...\") specific to this change, grouped under: Correctness, Tests, Security and privacy, Performance, Compatibility and migrations, Observability, Readability.",
      "Each item names the file or function to look at and the question to answer, e.g. \"- [ ] orders.ts createOrder: what happens when the payment call times out?\"",
      "Skip groups that do not apply. At most 15 items, riskiest first within each group. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: false,
    builtIn: true,
  },

  // --------------------------------------------------------------- RELEASE
  {
    id: "commit-message-repo-style",
    name: "Commit message in this repo's style",
    description: "Writes a commit message for the staged changes that follows the repository's own recent commit style, for developers.",
    phase: "release",
    roles: ["developer"],
    slash: "commitmsg",
    context: ["diff", "gitlog"],
    requiresContext: true,
    prompt: [
      "You are a developer writing a commit message.",
      "Intent from the author: {{input}}",
      "If recent commit history is provided, copy its conventions exactly: prefix style (e.g. Conventional Commits with scope), tense, capitalisation, subject length and body style. Otherwise use \"type(scope): subject\".",
      "Subject: imperative, max 72 characters, no trailing period. Then a blank line and a body wrapped at 72 characters explaining why, plus notable side effects.",
      "Output ONLY the commit message text - no code fence, no preamble. Do not mention anything the diff does not show; if the reason for the change is unclear, describe what changed rather than guessing why.",
    ].join("\n"),
    output: { kind: "markdown", offerCommitMessage: true },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "release-notes-from-commits",
    name: "Release notes from recent commits",
    description: "Turns recent commits into user-facing release notes grouped by impact, for product managers and DevOps.",
    phase: "release",
    roles: ["product", "devops", "developer"],
    slash: "relnotes",
    context: ["gitlog", "diff"],
    requiresContext: true,
    prompt: [
      "You are a product manager writing release notes for users.",
      "Version, audience or date range: {{input}}",
      "Output Markdown:",
      "# Release <version or \"notes\">",
      "## Highlights - up to three sentences on what users will notice.",
      "## New, ## Improved, ## Fixed - one plain-language bullet per user-visible change.",
      "## Breaking changes and upgrade steps - only if any.",
      "Leave out internal refactors, CI and test-only commits. Do not invent version numbers, dates or features that the commits do not show. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown", offerNewFile: true, languageId: "markdown" },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "changelog-entry",
    name: "Changelog entry",
    description: "Writes a Keep a Changelog style entry for the changes, ready to paste into CHANGELOG.md, for developers.",
    phase: "release",
    roles: ["developer", "product"],
    slash: "changelog",
    context: ["diff", "gitlog"],
    prompt: [
      "You are a maintainer updating CHANGELOG.md in Keep a Changelog format.",
      "Version and anything else to include: {{input}}",
      "Output only Markdown for one release:",
      "## [<version or Unreleased>] - <date if given, otherwise omit>",
      "then only the non-empty sections among ### Added, ### Changed, ### Deprecated, ### Removed, ### Fixed, ### Security.",
      "One concise bullet per change, written for people upgrading, with the issue or PR number if the material shows one.",
      "Do not invent versions, dates or issue numbers. " + UNSURE_INLINE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: true,
    builtIn: true,
  },

  // --------------------------------------------------------------- OPERATE
  {
    id: "log-stacktrace-analyser",
    name: "Analyse logs or a stack trace",
    description: "Finds the likely root cause in logs or a stack trace and lists the next checks, for DevOps and developers.",
    phase: "operate",
    roles: ["devops", "developer"],
    slash: "logs",
    context: ["terminal", "selection", "file"],
    prompt: [
      "You are an SRE analysing logs during an investigation.",
      "Logs, stack trace or symptom: {{input}}",
      "Output Markdown:",
      "**Signal:** the one or two lines that matter most, quoted exactly.",
      "**Likely root cause:** one paragraph, with a confidence level (high, medium, low) and the evidence.",
      "**Other candidates:** up to two, with what would rule each in or out.",
      "**Next checks:** numbered, concrete commands, queries or dashboards to look at, safest and cheapest first.",
      "**Mitigation:** a reversible step if users are affected now.",
      "Never suggest restarting, deleting or scaling down production as a first step. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "incident-postmortem-draft",
    name: "Blameless postmortem draft",
    description: "Drafts an incident summary or blameless postmortem from notes, a timeline or logs, for DevOps and SRE teams.",
    phase: "operate",
    roles: ["devops", "product"],
    slash: "postmortem",
    context: ["selection", "file", "terminal", "page"],
    prompt: [
      "You are an SRE writing a blameless postmortem.",
      "Incident notes: {{input}}",
      "Output Markdown in this template:",
      "# Incident: <title>",
      "**Status / Severity / Duration / Customer impact** - one line each, \"unknown\" if not given.",
      "## Summary - three sentences.",
      "## Timeline - table Time | Event, times exactly as given.",
      "## Root cause and contributing factors",
      "## Detection and response - what worked, what slowed us down.",
      "## Action items - table Action | Type (prevent, detect, mitigate) | Owner (\"TBD\") | Priority.",
      "Describe systems and decisions, never blame individuals. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown", offerNewFile: true, languageId: "markdown" },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "runbook-draft",
    name: "Runbook draft",
    description: "Drafts an operational runbook for a service or procedure with checks, steps, verification and rollback, for DevOps.",
    phase: "operate",
    roles: ["devops", "developer"],
    slash: "runbook",
    context: ["file", "selection", "terminal"],
    prompt: [
      "You are an SRE writing a runbook an on-call engineer can follow at 3 a.m.",
      "Service or procedure: {{input}}",
      "Output Markdown in this template:",
      "# Runbook: <name>",
      "## When to use - symptoms or alerts that lead here.",
      "## Prerequisites - access, tools, approvals.",
      "## Pre-checks - read-only commands confirming the current state.",
      "## Steps - numbered; each has the exact command in a code block and the expected result.",
      "## Verify - how to confirm success.",
      "## Rollback - how to undo each risky step.",
      "## Escalation - who or which team (\"TBD\" if unknown).",
      "Mark destructive steps with WARNING and require a confirmation. " + UNSURE,
    ].join("\n"),
    output: { kind: "markdown", offerNewFile: true, languageId: "markdown" },
    localFriendly: true,
    builtIn: true,
  },

  // -------------------------------------------------------------- AUTOMATE
  {
    id: "workflow-brief",
    name: "Turn this into a workflow",
    description: "Converts a repeated manual process into a workflow brief (trigger, inputs, steps, approvals, outputs) ready to automate, for product and DevOps.",
    phase: "automate",
    roles: ["product", "devops", "developer"],
    slash: "workflow",
    context: ["selection", "file", "page"],
    prompt: [
      "You are an automation architect turning a manual process into a workflow brief.",
      "Process to automate: {{input}}",
      "Output Markdown:",
      "## Goal - one sentence.",
      "## Trigger - schedule, event or manual, and its source.",
      "## Inputs - table Name | Type | Required | Example.",
      "## Steps - numbered; for each: action, system or tool used, and what happens on failure (retry, skip, stop).",
      "## Human approvals - which steps need sign-off and by whom.",
      "## Outputs and notifications",
      "## Guardrails - data it must not touch, rate or cost limits.",
      UNSURE,
    ].join("\n"),
    output: { kind: "markdown", offerWorkflow: true },
    localFriendly: true,
    builtIn: true,
  },
  {
    id: "standup-from-commits",
    name: "Standup from recent commits",
    description: "Drafts a yesterday / today / blockers standup update from recent commits, for developers.",
    phase: "automate",
    roles: ["developer", "tester"],
    slash: "standup",
    context: ["gitlog", "diff"],
    requiresContext: true,
    prompt: [
      "You are helping a developer prepare a short standup update.",
      "Author name, date range or plans for today: {{input}}",
      "If an author is named, use only their commits.",
      "Output Markdown with three headings: **Done**, **Next**, **Blockers**.",
      "Done: up to five bullets summarising outcomes, not individual commits, in plain language a product manager understands.",
      "Next: only what the user said or what work in progress clearly implies (e.g. uncommitted changes); otherwise \"(fill in)\".",
      "Blockers: only what the material shows; otherwise \"None mentioned\".",
      "Keep it readable in under 30 seconds. " + UNSURE_INLINE,
    ].join("\n"),
    output: { kind: "markdown" },
    localFriendly: true,
    builtIn: true,
  },
];
